JavaScript:
  beautifiers:
    - Prettier
    - Pretty Diff
    - JS-Beautify
    - ESLint
  align_assignments: !<tag:yaml.org,2002:js/undefined> ''
  arrow_parens: always
  brace_style: collapse-preserve-inline
  break_chained_methods: !<tag:yaml.org,2002:js/undefined> ''
  comma_first: !<tag:yaml.org,2002:js/undefined> ''
  end_with_newline: !<tag:yaml.org,2002:js/undefined> ''
  indent_comments: !<tag:yaml.org,2002:js/undefined> ''
  pragma_insert: !<tag:yaml.org,2002:js/undefined> ''
  quotes: !<tag:yaml.org,2002:js/undefined> ''
